services:
  - type: web
    name: bot-socavoness
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_socavones.py
    envVars:
      - key: TOKEN
        sync: false
      - key: ADMIN_USERS  
        sync: false
      - key: IMGBB_API_KEY

        sync: false


